

USE FoodieFiesta;

-- -------------------------------------
-- Business Question 1: What is the total revenue generated by each restaurant?
-- -------------------------------------
SELECT
    r.Name AS RestaurantName,
    SUM(o.FinalAmount) AS TotalRevenue
FROM Orders o
JOIN Restaurants r ON o.RestaurantID = r.RestaurantID
WHERE o.Status = 'Delivered'
GROUP BY r.Name
ORDER BY TotalRevenue DESC;


-- -------------------------------------
-- Business Question 2: Who are the top 3 most active customers (by number of orders)?
-- -------------------------------------
SELECT
    c.FirstName,
    c.LastName,
    COUNT(o.OrderID) AS NumberOfOrders
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID
GROUP BY c.CustomerID
ORDER BY NumberOfOrders DESC
LIMIT 3;


-- -------------------------------------
-- Business Question 3: What is the most popular menu item across all restaurants?
-- -------------------------------------
SELECT
    mi.Name AS MenuItem,
    r.Name AS Restaurant,
    SUM(od.Quantity) AS TotalQuantitySold
FROM OrderDetails od
JOIN MenuItems mi ON od.MenuItemID = mi.MenuItemID
JOIN Restaurants r ON mi.RestaurantID = r.RestaurantID
GROUP BY mi.MenuItemID
ORDER BY TotalQuantitySold DESC
LIMIT 1;


-- -------------------------------------
-- Business Question 4: What is the average order rating for each restaurant?
-- -------------------------------------
SELECT
    r.Name AS RestaurantName,
    AVG(o.OrderRating) AS AverageRating
FROM Orders o
JOIN Restaurants r ON o.RestaurantID = r.RestaurantID
WHERE o.OrderRating IS NOT NULL
GROUP BY r.Name
ORDER BY AverageRating DESC;


-- -------------------------------------
-- Business Question 5: List all orders from a specific customer (e.g., Priya Sharma)
-- with the restaurant name and final amount.
-- -------------------------------------
SELECT
    o.OrderID,
    o.OrderDate,
    r.Name AS Restaurant,
    o.FinalAmount,
    o.Status
FROM Orders o
JOIN Restaurants r ON o.RestaurantID = r.RestaurantID
JOIN Customers c ON o.CustomerID = c.CustomerID
WHERE c.FirstName = 'Priya' AND c.LastName = 'Sharma'
ORDER BY o.OrderDate DESC;
